### ISSUE TITLE
Error [ED-06]

### ISSUE THREAD

**Issue by jh4xsy** [SSSRC/hirogari-decoder#3]
I built direwolf and  "yarn start" your software.
When I pushed decoder button, I got "Failed to decode" error.

See also my log. [log_20210630173558013.log](https://github.com/SSSRC/hirogari-decoder/files/6745176/log_20210630173558013.log)

**Comment by wowry** [comment]
@jh4xsy 
本ソフトウェアをご利用いただきありがとうございます！
ご対応が遅くなり大変申し訳ありません。

ご報告頂いたエラーに関しまして、下記の2点をご確認いただきますようお願い致します。
- ビルドしたdirewolfの`atest`ファイルが`decoder/build/linux`内に配置されている
- 配置した`atest`ファイルのパーミッションが755である

**Comment by jh4xsy** [comment]
@wowry さん，確認結果を送ります。

- atestは decoder/build/linux に配置されてました
- そのatestのパーミッションは755でした

**Comment by jh4xsy** [comment]
HIROGARI-Decoder-1.2.0-linux.rpm をインストールしましたが，同じ結果になりました。LinuxはopenSUSE 15.2を使っています。

**Comment by wowry** [comment]
@jh4xsy 様
ご確認いただきありがとうございます。
頂いた情報から、本ソフトウェアの現在のバージョンがopenSUSEでの動作をサポートできていないものと思われます。
ご不便をおかけし誠に申し訳ございません。

こちらのコマンドを実行した際にエラーが出る場合、本ソフトウェアはデコード処理を正常に実行できません。
`./decoder/build/linux/server {任意のポート番号}`
(e.g. `./decoder/build/linux/server 8080`)

上記のコマンドでエラーが出る場合、お手数ですが下記手順にて`server`ファイルのビルドを行っていただけないでしょうか。
1. Python3環境を用意する
2. `pip3 install pyinstaller flask`
3. `python3 decoder/src/server.py {任意のポート番号}`を実行し、エラーが出ないことを確認する
4. `pyinstaller decoder/src/server.py --onefile --clean`
5. `mv decoder/src/dist/server decoder/build/linux/server`
6. 再度、`./decoder/build/linux/server {任意のポート番号}`を実行し、エラーが出ないことを確認する

**Comment by jh4xsy** [comment]
@wowry さん

serverをビルドし直したら，デコーダが起動できました。どうも有難うございます。

ちなみにopenSUSEでは，serverはdistに出力されました。

```
% dist/server 88888
 * Serving Flask app 'server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:23352/ (Press CTRL+C to quit)

**Comment by wowry** [comment]
@jh4xsy 様
ご対応いただきありがとうございました！
また、貴重な情報をご提供いただきありがとうございます。

より利便性の高いソフトウェアを目指してアップデートしていく所存ですので、
引き続きよろしくお願い申し上げます。
